#!/bin/bash
#SBATCH --job-name=Sort_Index_SM_BAMs
#SBATCH --time=96:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=4
#SBATCH --mem=96G
#SBATCH --output=Sort_Index_SM_BAMs.out
#SBATCH --error=Sort_Index_SM_BAMs.err
#SBATCH --mail-user=tjweide@iastate.edu
#SBATCH --mail-type=END,FAIL

module load samtools

cd /work/ABG/tjweide/Genomics/Mito_WGS_2025/Merged

# === Sorting .SM.bam files (in parallel) ===
samtools sort -@ 4 -o 1.merged.SM.sorted.bam 1.merged.SM.bam &
samtools sort -@ 4 -o 2.merged.SM.sorted.bam 2.merged.SM.bam &
samtools sort -@ 4 -o 3.merged.SM.sorted.bam 3.merged.SM.bam &

wait

# === Indexing .SM.sorted.bam files (in parallel) ===
samtools index -@ 4 1.merged.SM.sorted.bam &
samtools index -@ 4 2.merged.SM.sorted.bam &
samtools index -@ 4 3.merged.SM.sorted.bam &

wait
