#!/bin/bash
#SBATCH --job-name=filter_individual_final
#SBATCH --output=filter_individual_final.out
#SBATCH --error=filter_individual_final.err
#SBATCH --cpus-per-task=6
#SBATCH --time=36:00:00
#SBATCH --mail-user=tjweide@iastate.edu
#SBATCH --mail-type=END,FAIL

module load bcftools

IN_DIR="/work/ABG/tjweide/Genomics/Mito_WGS_2025/VCF/Genotyped/Filtered/Individual"
OUT_DIR="/work/ABG/tjweide/Genomics/Mito_WGS_2025/VCF/Genotyped/Filtered/Individual/Final"

# Filtering all 6 individuals
bcftools view -v snps -f PASS ${IN_DIR}/1-1.filtered.vcf.gz | \
bcftools filter -i 'FMT/GQ>=20 && FMT/DP>=20 && FMT/DP<=60' \
-Oz -o ${OUT_DIR}/1-1.final.vcf.gz &

bcftools view -v snps -f PASS ${IN_DIR}/1-2.filtered.vcf.gz | \
bcftools filter -i 'FMT/GQ>=20 && FMT/DP>=20 && FMT/DP<=60' \
-Oz -o ${OUT_DIR}/1-2.final.vcf.gz &

bcftools view -v snps -f PASS ${IN_DIR}/2-1.filtered.vcf.gz | \
bcftools filter -i 'FMT/GQ>=20 && FMT/DP>=20 && FMT/DP<=60' \
-Oz -o ${OUT_DIR}/2-1.final.vcf.gz &

bcftools view -v snps -f PASS ${IN_DIR}/2-2.filtered.vcf.gz | \
bcftools filter -i 'FMT/GQ>=20 && FMT/DP>=20 && FMT/DP<=60' \
-Oz -o ${OUT_DIR}/2-2.final.vcf.gz &

bcftools view -v snps -f PASS ${IN_DIR}/3-1.filtered.vcf.gz | \
bcftools filter -i 'FMT/GQ>=20 && FMT/DP>=20 && FMT/DP<=60' \
-Oz -o ${OUT_DIR}/3-1.final.vcf.gz &

bcftools view -v snps -f PASS ${IN_DIR}/3-2.filtered.vcf.gz | \
bcftools filter -i 'FMT/GQ>=20 && FMT/DP>=20 && FMT/DP<=60' \
-Oz -o ${OUT_DIR}/3-2.final.vcf.gz &

wait

# Index all outputs
for ID in 1-1 1-2 2-1 2-2 3-1 3-2; do
    tabix -p vcf ${OUT_DIR}/${ID}.final.vcf.gz &
done

wait

